pages = [{"l":"api/index.html","n":"little-sql","t":"little-sql","d":"","k":"static"},
{"l":"api/little/sql.html","n":"little.sql","t":"package little.sql","d":"little/sql","k":"package"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"GetBigDecimal","t":"given GetBigDecimal: GetValue[BigDecimal]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): BigDecimal","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): BigDecimal","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetBoolean$.html","n":"GetBoolean","t":"given GetBoolean: GetValue[Boolean]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Boolean","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Boolean","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetByte$.html","n":"GetByte","t":"given GetByte: GetValue[Byte]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Byte","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Byte","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetDate$.html","n":"GetDate","t":"given GetDate: GetValue[Date]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Date","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Date","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetDouble$.html","n":"GetDouble","t":"given GetDouble: GetValue[Double]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Double","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Double","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetFloat$.html","n":"GetFloat","t":"given GetFloat: GetValue[Float]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Float","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Float","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetInstant$.html","n":"GetInstant","t":"given GetInstant: GetValue[Instant]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Instant","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Instant","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetInt$.html","n":"GetInt","t":"given GetInt: GetValue[Int]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Int","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Int","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalDate$.html","n":"GetLocalDate","t":"given GetLocalDate: GetValue[LocalDate]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDate","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDate","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"GetLocalDateTime","t":"given GetLocalDateTime: GetValue[LocalDateTime]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDateTime","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDateTime","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalTime$.html","n":"GetLocalTime","t":"given GetLocalTime: GetValue[LocalTime]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalTime","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalTime","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLong$.html","n":"GetLong","t":"given GetLong: GetValue[Long]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Long","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Long","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetShort$.html","n":"GetShort","t":"given GetShort: GetValue[Short]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Short","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Short","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetString$.html","n":"GetString","t":"given GetString: GetValue[String]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): String","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): String","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetTime$.html","n":"GetTime","t":"given GetTime: GetValue[Time]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Time","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Time","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetTimestamp$.html","n":"GetTimestamp","t":"given GetTimestamp: GetValue[Timestamp]","d":"little/sql","k":"given"},
{"l":"api/little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Timestamp","d":"little/sql","k":"def"},
{"l":"api/little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Timestamp","d":"little/sql","k":"def"},
{"l":"api/little/sql/anyToInParam$.html","n":"anyToInParam","t":"given anyToInParam: Conversion[Any, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/anyToInParam$.html","n":"apply","t":"def apply(value: Any): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/bigDecimalToInParam$.html","n":"bigDecimalToInParam","t":"given bigDecimalToInParam: Conversion[BigDecimal, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/bigDecimalToInParam$.html","n":"apply","t":"def apply(value: BigDecimal): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/booleanToInParam$.html","n":"booleanToInParam","t":"given booleanToInParam: Conversion[Boolean, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/booleanToInParam$.html","n":"apply","t":"def apply(value: Boolean): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/byteToInParam$.html","n":"byteToInParam","t":"given byteToInParam: Conversion[Byte, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/byteToInParam$.html","n":"apply","t":"def apply(value: Byte): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/dateToInParam$.html","n":"dateToInParam","t":"given dateToInParam: Conversion[Date, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/dateToInParam$.html","n":"apply","t":"def apply(value: Date): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/doubleToInParam$.html","n":"doubleToInParam","t":"given doubleToInParam: Conversion[Double, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/doubleToInParam$.html","n":"apply","t":"def apply(value: Double): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/floatToInParam$.html","n":"floatToInParam","t":"given floatToInParam: Conversion[Float, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/floatToInParam$.html","n":"apply","t":"def apply(value: Float): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/instantToInParam$.html","n":"instantToInParam","t":"given instantToInParam: Conversion[Instant, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/instantToInParam$.html","n":"apply","t":"def apply(value: Instant): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/intToInParam$.html","n":"intToInParam","t":"given intToInParam: Conversion[Int, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/intToInParam$.html","n":"apply","t":"def apply(value: Int): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/localDateTimeToInParam$.html","n":"localDateTimeToInParam","t":"given localDateTimeToInParam: Conversion[LocalDateTime, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/localDateTimeToInParam$.html","n":"apply","t":"def apply(value: LocalDateTime): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/localDateToInParam$.html","n":"localDateToInParam","t":"given localDateToInParam: Conversion[LocalDate, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/localDateToInParam$.html","n":"apply","t":"def apply(value: LocalDate): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/localTimeToInParam$.html","n":"localTimeToInParam","t":"given localTimeToInParam: Conversion[LocalTime, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/localTimeToInParam$.html","n":"apply","t":"def apply(value: LocalTime): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/longToInParam$.html","n":"longToInParam","t":"given longToInParam: Conversion[Long, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/longToInParam$.html","n":"apply","t":"def apply(value: Long): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/mapToMapInParam.html","n":"mapToMapInParam","t":"given mapToMapInParam[T](using val convert: Conversion[T, InParam]): Conversion[Map[String, T], Map[String, InParam]]","d":"little/sql","k":"given"},
{"l":"api/little/sql/mapToMapInParam.html","n":"apply","t":"def apply(values: Map[String, T]): Map[String, InParam]","d":"little/sql","k":"def"},
{"l":"api/little/sql/mapToMapInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql","k":"val"},
{"l":"api/little/sql/optionToInParam.html","n":"optionToInParam","t":"given optionToInParam[T](using val convert: Conversion[T, InParam]): Conversion[Option[T], InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/optionToInParam.html","n":"apply","t":"def apply(value: Option[T]): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/optionToInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql","k":"val"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"seqToSeqInParam","t":"given seqToSeqInParam[T](using val convert: Conversion[T, InParam]): Conversion[Seq[T], Seq[InParam]]","d":"little/sql","k":"given"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"apply","t":"def apply(values: Seq[T]): Seq[InParam]","d":"little/sql","k":"def"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql","k":"val"},
{"l":"api/little/sql/shortToInParam$.html","n":"shortToInParam","t":"given shortToInParam: Conversion[Short, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/shortToInParam$.html","n":"apply","t":"def apply(value: Short): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/stringToInParam$.html","n":"stringToInParam","t":"given stringToInParam: Conversion[String, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/stringToInParam$.html","n":"apply","t":"def apply(value: String): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/timeToInParam$.html","n":"timeToInParam","t":"given timeToInParam: Conversion[Time, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/timeToInParam$.html","n":"apply","t":"def apply(value: Time): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/timestampToInParam$.html","n":"timestampToInParam","t":"given timestampToInParam: Conversion[Timestamp, InParam]","d":"little/sql","k":"given"},
{"l":"api/little/sql/timestampToInParam$.html","n":"apply","t":"def apply(value: Timestamp): InParam","d":"little/sql","k":"def"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"tupleToTupleInParam","t":"given tupleToTupleInParam[T](using val convert: Conversion[T, InParam]): Conversion[(String, T), (String, InParam)]","d":"little/sql","k":"given"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"apply","t":"def apply(value: (String, T)): (String, InParam)","d":"little/sql","k":"def"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql","k":"val"},
{"l":"api/little/sql/ConnectionExt.html","n":"ConnectionExt","t":"class ConnectionExt(connection: Connection) extends AnyVal","d":"little/sql/ConnectionExt","k":"class"},
{"l":"api/little/sql/ConnectionExt.html","n":"batch","t":"def batch(generator: () => Iterable[String]): Array[Int]","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"batch","t":"def batch(sql: String)(generator: () => Iterable[Seq[InParam]]): Array[Int]","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"execute","t":"def execute[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: Execution => T): T","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"first","t":"def first[T](sql: String, params: Seq[InParam], queryTimeout: Int)(f: ResultSet => T): Option[T]","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"flatMap","t":"def flatMap[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"foreach","t":"def foreach(sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Unit): Unit","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"map","t":"def map[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): Seq[T]","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"query","t":"def query[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): T","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"update","t":"def update(sql: String, params: Seq[InParam], queryTimeout: Int): Long","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"withPreparedStatement","t":"def withPreparedStatement[T](sql: String)(f: PreparedStatement => T): T","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/ConnectionExt.html","n":"withStatement","t":"def withStatement[T](f: Statement => T): T","d":"little/sql/ConnectionExt","k":"def"},
{"l":"api/little/sql/Connector.html","n":"Connector","t":"class Connector(url: String, user: String, password: String, driverClassName: String)","d":"little/sql/Connector","k":"class"},
{"l":"api/little/sql/Connector.html","n":"getConnection","t":"def getConnection(): Connection","d":"little/sql/Connector","k":"def"},
{"l":"api/little/sql/Connector.html","n":"withConnection","t":"def withConnection[T](f: Connection => T): T","d":"little/sql/Connector","k":"def"},
{"l":"api/little/sql/DataSourceExt.html","n":"DataSourceExt","t":"class DataSourceExt(dataSource: DataSource) extends AnyVal","d":"little/sql/DataSourceExt","k":"class"},
{"l":"api/little/sql/DataSourceExt.html","n":"withConnection","t":"def withConnection[T](f: Connection => T): T","d":"little/sql/DataSourceExt","k":"def"},
{"l":"api/little/sql/DataSourceExt.html","n":"withConnection","t":"def withConnection[T](user: String, password: String)(f: Connection => T): T","d":"little/sql/DataSourceExt","k":"def"},
{"l":"api/little/sql/Execution.html","n":"Execution","t":"class Execution","d":"little/sql/Execution","k":"class"},
{"l":"api/little/sql/Execution.html","n":"count","t":"def count: Int","d":"little/sql/Execution","k":"def"},
{"l":"api/little/sql/Execution.html","n":"isQuery","t":"def isQuery: Boolean","d":"little/sql/Execution","k":"def"},
{"l":"api/little/sql/Execution.html","n":"isUpdate","t":"def isUpdate: Boolean","d":"little/sql/Execution","k":"def"},
{"l":"api/little/sql/Execution.html","n":"resultSet","t":"def resultSet: ResultSet","d":"little/sql/Execution","k":"def"},
{"l":"api/little/sql/Execution$.html","n":"Execution","t":"object Execution","d":"little/sql/Execution$","k":"object"},
{"l":"api/little/sql/Execution$.html","n":"apply","t":"def apply(count: Int): Update","d":"little/sql/Execution$","k":"def"},
{"l":"api/little/sql/Execution$.html","n":"apply","t":"def apply(resultSet: ResultSet): Query","d":"little/sql/Execution$","k":"def"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"GetBigDecimal","t":"given GetBigDecimal: GetValue[BigDecimal]","d":"little/sql/GetBigDecimal$","k":"given"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): BigDecimal","d":"little/sql/GetBigDecimal$","k":"def"},
{"l":"api/little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): BigDecimal","d":"little/sql/GetBigDecimal$","k":"def"},
{"l":"api/little/sql/GetBoolean$.html","n":"GetBoolean","t":"given GetBoolean: GetValue[Boolean]","d":"little/sql/GetBoolean$","k":"given"},
{"l":"api/little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Boolean","d":"little/sql/GetBoolean$","k":"def"},
{"l":"api/little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Boolean","d":"little/sql/GetBoolean$","k":"def"},
{"l":"api/little/sql/GetByte$.html","n":"GetByte","t":"given GetByte: GetValue[Byte]","d":"little/sql/GetByte$","k":"given"},
{"l":"api/little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Byte","d":"little/sql/GetByte$","k":"def"},
{"l":"api/little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Byte","d":"little/sql/GetByte$","k":"def"},
{"l":"api/little/sql/GetDate$.html","n":"GetDate","t":"given GetDate: GetValue[Date]","d":"little/sql/GetDate$","k":"given"},
{"l":"api/little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Date","d":"little/sql/GetDate$","k":"def"},
{"l":"api/little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Date","d":"little/sql/GetDate$","k":"def"},
{"l":"api/little/sql/GetDouble$.html","n":"GetDouble","t":"given GetDouble: GetValue[Double]","d":"little/sql/GetDouble$","k":"given"},
{"l":"api/little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Double","d":"little/sql/GetDouble$","k":"def"},
{"l":"api/little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Double","d":"little/sql/GetDouble$","k":"def"},
{"l":"api/little/sql/GetFloat$.html","n":"GetFloat","t":"given GetFloat: GetValue[Float]","d":"little/sql/GetFloat$","k":"given"},
{"l":"api/little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Float","d":"little/sql/GetFloat$","k":"def"},
{"l":"api/little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Float","d":"little/sql/GetFloat$","k":"def"},
{"l":"api/little/sql/GetInstant$.html","n":"GetInstant","t":"given GetInstant: GetValue[Instant]","d":"little/sql/GetInstant$","k":"given"},
{"l":"api/little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Instant","d":"little/sql/GetInstant$","k":"def"},
{"l":"api/little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Instant","d":"little/sql/GetInstant$","k":"def"},
{"l":"api/little/sql/GetInt$.html","n":"GetInt","t":"given GetInt: GetValue[Int]","d":"little/sql/GetInt$","k":"given"},
{"l":"api/little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Int","d":"little/sql/GetInt$","k":"def"},
{"l":"api/little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Int","d":"little/sql/GetInt$","k":"def"},
{"l":"api/little/sql/GetLocalDate$.html","n":"GetLocalDate","t":"given GetLocalDate: GetValue[LocalDate]","d":"little/sql/GetLocalDate$","k":"given"},
{"l":"api/little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDate","d":"little/sql/GetLocalDate$","k":"def"},
{"l":"api/little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDate","d":"little/sql/GetLocalDate$","k":"def"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"GetLocalDateTime","t":"given GetLocalDateTime: GetValue[LocalDateTime]","d":"little/sql/GetLocalDateTime$","k":"given"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDateTime","d":"little/sql/GetLocalDateTime$","k":"def"},
{"l":"api/little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDateTime","d":"little/sql/GetLocalDateTime$","k":"def"},
{"l":"api/little/sql/GetLocalTime$.html","n":"GetLocalTime","t":"given GetLocalTime: GetValue[LocalTime]","d":"little/sql/GetLocalTime$","k":"given"},
{"l":"api/little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalTime","d":"little/sql/GetLocalTime$","k":"def"},
{"l":"api/little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalTime","d":"little/sql/GetLocalTime$","k":"def"},
{"l":"api/little/sql/GetLong$.html","n":"GetLong","t":"given GetLong: GetValue[Long]","d":"little/sql/GetLong$","k":"given"},
{"l":"api/little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Long","d":"little/sql/GetLong$","k":"def"},
{"l":"api/little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Long","d":"little/sql/GetLong$","k":"def"},
{"l":"api/little/sql/GetShort$.html","n":"GetShort","t":"given GetShort: GetValue[Short]","d":"little/sql/GetShort$","k":"given"},
{"l":"api/little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Short","d":"little/sql/GetShort$","k":"def"},
{"l":"api/little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Short","d":"little/sql/GetShort$","k":"def"},
{"l":"api/little/sql/GetString$.html","n":"GetString","t":"given GetString: GetValue[String]","d":"little/sql/GetString$","k":"given"},
{"l":"api/little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): String","d":"little/sql/GetString$","k":"def"},
{"l":"api/little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): String","d":"little/sql/GetString$","k":"def"},
{"l":"api/little/sql/GetTime$.html","n":"GetTime","t":"given GetTime: GetValue[Time]","d":"little/sql/GetTime$","k":"given"},
{"l":"api/little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Time","d":"little/sql/GetTime$","k":"def"},
{"l":"api/little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Time","d":"little/sql/GetTime$","k":"def"},
{"l":"api/little/sql/GetTimestamp$.html","n":"GetTimestamp","t":"given GetTimestamp: GetValue[Timestamp]","d":"little/sql/GetTimestamp$","k":"given"},
{"l":"api/little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Timestamp","d":"little/sql/GetTimestamp$","k":"def"},
{"l":"api/little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Timestamp","d":"little/sql/GetTimestamp$","k":"def"},
{"l":"api/little/sql/GetValue.html","n":"GetValue","t":"trait GetValue[T] extends GetValueByIndex[T] with GetValueByLabel[T]","d":"little/sql/GetValue","k":"trait"},
{"l":"api/little/sql/GetValueByIndex.html","n":"GetValueByIndex","t":"trait GetValueByIndex[T]","d":"little/sql/GetValueByIndex","k":"trait"},
{"l":"api/little/sql/GetValueByIndex.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): T","d":"little/sql/GetValueByIndex","k":"def"},
{"l":"api/little/sql/GetValueByLabel.html","n":"GetValueByLabel","t":"trait GetValueByLabel[T]","d":"little/sql/GetValueByLabel","k":"trait"},
{"l":"api/little/sql/GetValueByLabel.html","n":"apply","t":"def apply(rs: ResultSet, label: String): T","d":"little/sql/GetValueByLabel","k":"def"},
{"l":"api/little/sql/InParam.html","n":"InParam","t":"trait InParam","d":"little/sql/InParam","k":"trait"},
{"l":"api/little/sql/InParam.html","n":"isNull","t":"def isNull: Boolean","d":"little/sql/InParam","k":"def"},
{"l":"api/little/sql/InParam.html","n":"sqlType","t":"def sqlType: Int","d":"little/sql/InParam","k":"def"},
{"l":"api/little/sql/InParam.html","n":"value","t":"def value: Any","d":"little/sql/InParam","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"InParam","t":"object InParam","d":"little/sql/InParam$","k":"object"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply[T](value: T, isNull: Boolean, sqlType: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply[T](value: T, sqlType: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: String): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Boolean): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Byte): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Short): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Long): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Float): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Double): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: BigDecimal): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Date): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Time): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Timestamp): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalDate): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalTime): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalDateTime): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$.html","n":"apply","t":"def apply(value: Instant): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"api/little/sql/InParam$$Null$.html","n":"Null","t":"object Null extends InParam","d":"little/sql/InParam$$Null$","k":"object"},
{"l":"api/little/sql/InParam$$Null$.html","n":"isNull","t":"val isNull: Boolean","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"api/little/sql/InParam$$Null$.html","n":"sqlType","t":"val sqlType: Int","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"api/little/sql/InParam$$Null$.html","n":"value","t":"val value: Any","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"PreparedStatementExt","t":"class PreparedStatementExt(statement: PreparedStatement) extends AnyVal","d":"little/sql/PreparedStatementExt","k":"class"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"addBatch","t":"def addBatch(params: Seq[InParam]): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"execute","t":"def execute[T](params: Seq[InParam])(f: Execution => T): T","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"first","t":"def first[T](params: Seq[InParam])(f: ResultSet => T): Option[T]","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"flatMap","t":"def flatMap[T](params: Seq[InParam])(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"foreach","t":"def foreach(params: Seq[InParam])(f: ResultSet => Unit): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"map","t":"def map[T](params: Seq[InParam])(f: ResultSet => T): Seq[T]","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"query","t":"def query[T](params: Seq[InParam])(f: ResultSet => T): T","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"set","t":"def set(index: Int, value: InParam): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"set","t":"def set(params: Seq[InParam]): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"setInstant","t":"def setInstant(index: Int, value: Instant): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"setLocalDate","t":"def setLocalDate(index: Int, value: LocalDate): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"setLocalDateTime","t":"def setLocalDateTime(index: Int, value: LocalDateTime): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"setLocalTime","t":"def setLocalTime(index: Int, value: LocalTime): Unit","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/PreparedStatementExt.html","n":"update","t":"def update(params: Seq[InParam]): Int","d":"little/sql/PreparedStatementExt","k":"def"},
{"l":"api/little/sql/Query.html","n":"Query","t":"class Query(resultSet: ResultSet) extends Execution","d":"little/sql/Query","k":"class"},
{"l":"api/little/sql/Query.html","n":"count","t":"def count: Int","d":"little/sql/Query","k":"def"},
{"l":"api/little/sql/Query.html","n":"isQuery","t":"val isQuery: Boolean","d":"little/sql/Query","k":"val"},
{"l":"api/little/sql/Query.html","n":"isUpdate","t":"val isUpdate: Boolean","d":"little/sql/Query","k":"val"},
{"l":"api/little/sql/QueryBuilder.html","n":"QueryBuilder","t":"trait QueryBuilder","d":"little/sql/QueryBuilder","k":"trait"},
{"l":"api/little/sql/QueryBuilder.html","n":"execute","t":"def execute[T](handler: Execution => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"fetchSize","t":"def fetchSize: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"fetchSize","t":"def fetchSize(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"first","t":"def first[T](f: ResultSet => T)(using conn: Connection): Option[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"flatMap","t":"def flatMap[T](f: ResultSet => Iterable[T])(using conn: Connection): Seq[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"fold","t":"def fold[T](init: T)(op: (T, ResultSet) => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"foreach","t":"def foreach(f: ResultSet => Unit)(using conn: Connection): Unit","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"getUpdateCount","t":"def getUpdateCount(using conn: Connection): Long","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"map","t":"def map[T](f: ResultSet => T)(using conn: Connection): Seq[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"maxRows","t":"def maxRows: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"maxRows","t":"def maxRows(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"params","t":"def params: Seq[InParam]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"params","t":"def params(values: Seq[InParam]): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"params","t":"def params(one: InParam, more: InParam*): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"params","t":"def params(values: Map[String, InParam]): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"params","t":"def params(one: (String, InParam), more: (String, InParam)*): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"queryTimeout","t":"def queryTimeout: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"queryTimeout","t":"def queryTimeout(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"sql","t":"def sql: String","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder.html","n":"withResultSet","t":"def withResultSet[T](handler: ResultSet => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"api/little/sql/QueryBuilder$.html","n":"QueryBuilder","t":"object QueryBuilder","d":"little/sql/QueryBuilder$","k":"object"},
{"l":"api/little/sql/QueryBuilder$.html","n":"apply","t":"def apply(sql: String): QueryBuilder","d":"little/sql/QueryBuilder$","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"ResultSetExt","t":"class ResultSetExt(resultSet: ResultSet) extends AnyVal","d":"little/sql/ResultSetExt","k":"class"},
{"l":"api/little/sql/ResultSetExt.html","n":"flatMap","t":"def flatMap[T](f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"fold","t":"def fold[T](init: T)(op: (T, ResultSet) => T): T","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"foreach","t":"def foreach(f: ResultSet => Unit): Unit","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"get","t":"def get[T](index: Int)(using getValue: GetValueByIndex[T]): T","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"get","t":"def get[T](label: String)(using getValue: GetValueByLabel[T]): T","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getColumnCount","t":"def getColumnCount(): Int","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getColumnLabels","t":"def getColumnLabels(): Seq[String]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getInstant","t":"def getInstant(index: Int): Instant","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getInstant","t":"def getInstant(label: String): Instant","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalDate","t":"def getLocalDate(index: Int): LocalDate","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalDate","t":"def getLocalDate(label: String): LocalDate","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalDateTime","t":"def getLocalDateTime(index: Int): LocalDateTime","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalDateTime","t":"def getLocalDateTime(label: String): LocalDateTime","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalTime","t":"def getLocalTime(index: Int): LocalTime","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getLocalTime","t":"def getLocalTime(label: String): LocalTime","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getOption","t":"def getOption[T](index: Int)(using getValue: GetValueByIndex[T]): Option[T]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getOption","t":"def getOption[T](label: String)(using getValue: GetValueByLabel[T]): Option[T]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getOrElse","t":"def getOrElse[T](index: Int, default: => T)(using getValue: GetValueByIndex[T]): T","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"getOrElse","t":"def getOrElse[T](label: String, default: => T)(using getValue: GetValueByLabel[T]): T","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"map","t":"def map[T](f: ResultSet => T): Seq[T]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/ResultSetExt.html","n":"next","t":"def next[T](f: ResultSet => T): Option[T]","d":"little/sql/ResultSetExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"StatementExt","t":"class StatementExt(statement: Statement) extends AnyVal","d":"little/sql/StatementExt","k":"class"},
{"l":"api/little/sql/StatementExt.html","n":"execute","t":"def execute[T](sql: String)(f: Execution => T): T","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"first","t":"def first[T](sql: String)(f: ResultSet => T): Option[T]","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"flatMap","t":"def flatMap[T](sql: String)(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"foreach","t":"def foreach(sql: String)(f: ResultSet => Unit): Unit","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"map","t":"def map[T](sql: String)(f: ResultSet => T): Seq[T]","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/StatementExt.html","n":"query","t":"def query[T](sql: String)(f: ResultSet => T): T","d":"little/sql/StatementExt","k":"def"},
{"l":"api/little/sql/Update.html","n":"Update","t":"class Update(count: Int) extends Execution","d":"little/sql/Update","k":"class"},
{"l":"api/little/sql/Update.html","n":"isQuery","t":"val isQuery: Boolean","d":"little/sql/Update","k":"val"},
{"l":"api/little/sql/Update.html","n":"isUpdate","t":"val isUpdate: Boolean","d":"little/sql/Update","k":"val"},
{"l":"api/little/sql/Update.html","n":"resultSet","t":"def resultSet: ResultSet","d":"little/sql/Update","k":"def"},
{"l":"api/little/sql/anyToInParam$.html","n":"anyToInParam","t":"given anyToInParam: Conversion[Any, InParam]","d":"little/sql/anyToInParam$","k":"given"},
{"l":"api/little/sql/anyToInParam$.html","n":"apply","t":"def apply(value: Any): InParam","d":"little/sql/anyToInParam$","k":"def"},
{"l":"api/little/sql/bigDecimalToInParam$.html","n":"bigDecimalToInParam","t":"given bigDecimalToInParam: Conversion[BigDecimal, InParam]","d":"little/sql/bigDecimalToInParam$","k":"given"},
{"l":"api/little/sql/bigDecimalToInParam$.html","n":"apply","t":"def apply(value: BigDecimal): InParam","d":"little/sql/bigDecimalToInParam$","k":"def"},
{"l":"api/little/sql/booleanToInParam$.html","n":"booleanToInParam","t":"given booleanToInParam: Conversion[Boolean, InParam]","d":"little/sql/booleanToInParam$","k":"given"},
{"l":"api/little/sql/booleanToInParam$.html","n":"apply","t":"def apply(value: Boolean): InParam","d":"little/sql/booleanToInParam$","k":"def"},
{"l":"api/little/sql/byteToInParam$.html","n":"byteToInParam","t":"given byteToInParam: Conversion[Byte, InParam]","d":"little/sql/byteToInParam$","k":"given"},
{"l":"api/little/sql/byteToInParam$.html","n":"apply","t":"def apply(value: Byte): InParam","d":"little/sql/byteToInParam$","k":"def"},
{"l":"api/little/sql/dateToInParam$.html","n":"dateToInParam","t":"given dateToInParam: Conversion[Date, InParam]","d":"little/sql/dateToInParam$","k":"given"},
{"l":"api/little/sql/dateToInParam$.html","n":"apply","t":"def apply(value: Date): InParam","d":"little/sql/dateToInParam$","k":"def"},
{"l":"api/little/sql/doubleToInParam$.html","n":"doubleToInParam","t":"given doubleToInParam: Conversion[Double, InParam]","d":"little/sql/doubleToInParam$","k":"given"},
{"l":"api/little/sql/doubleToInParam$.html","n":"apply","t":"def apply(value: Double): InParam","d":"little/sql/doubleToInParam$","k":"def"},
{"l":"api/little/sql/floatToInParam$.html","n":"floatToInParam","t":"given floatToInParam: Conversion[Float, InParam]","d":"little/sql/floatToInParam$","k":"given"},
{"l":"api/little/sql/floatToInParam$.html","n":"apply","t":"def apply(value: Float): InParam","d":"little/sql/floatToInParam$","k":"def"},
{"l":"api/little/sql/instantToInParam$.html","n":"instantToInParam","t":"given instantToInParam: Conversion[Instant, InParam]","d":"little/sql/instantToInParam$","k":"given"},
{"l":"api/little/sql/instantToInParam$.html","n":"apply","t":"def apply(value: Instant): InParam","d":"little/sql/instantToInParam$","k":"def"},
{"l":"api/little/sql/intToInParam$.html","n":"intToInParam","t":"given intToInParam: Conversion[Int, InParam]","d":"little/sql/intToInParam$","k":"given"},
{"l":"api/little/sql/intToInParam$.html","n":"apply","t":"def apply(value: Int): InParam","d":"little/sql/intToInParam$","k":"def"},
{"l":"api/little/sql/localDateTimeToInParam$.html","n":"localDateTimeToInParam","t":"given localDateTimeToInParam: Conversion[LocalDateTime, InParam]","d":"little/sql/localDateTimeToInParam$","k":"given"},
{"l":"api/little/sql/localDateTimeToInParam$.html","n":"apply","t":"def apply(value: LocalDateTime): InParam","d":"little/sql/localDateTimeToInParam$","k":"def"},
{"l":"api/little/sql/localDateToInParam$.html","n":"localDateToInParam","t":"given localDateToInParam: Conversion[LocalDate, InParam]","d":"little/sql/localDateToInParam$","k":"given"},
{"l":"api/little/sql/localDateToInParam$.html","n":"apply","t":"def apply(value: LocalDate): InParam","d":"little/sql/localDateToInParam$","k":"def"},
{"l":"api/little/sql/localTimeToInParam$.html","n":"localTimeToInParam","t":"given localTimeToInParam: Conversion[LocalTime, InParam]","d":"little/sql/localTimeToInParam$","k":"given"},
{"l":"api/little/sql/localTimeToInParam$.html","n":"apply","t":"def apply(value: LocalTime): InParam","d":"little/sql/localTimeToInParam$","k":"def"},
{"l":"api/little/sql/longToInParam$.html","n":"longToInParam","t":"given longToInParam: Conversion[Long, InParam]","d":"little/sql/longToInParam$","k":"given"},
{"l":"api/little/sql/longToInParam$.html","n":"apply","t":"def apply(value: Long): InParam","d":"little/sql/longToInParam$","k":"def"},
{"l":"api/little/sql/mapToMapInParam.html","n":"mapToMapInParam","t":"given mapToMapInParam[T](using val convert: Conversion[T, InParam]): Conversion[Map[String, T], Map[String, InParam]]","d":"little/sql/mapToMapInParam","k":"given"},
{"l":"api/little/sql/mapToMapInParam.html","n":"apply","t":"def apply(values: Map[String, T]): Map[String, InParam]","d":"little/sql/mapToMapInParam","k":"def"},
{"l":"api/little/sql/mapToMapInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql/mapToMapInParam","k":"val"},
{"l":"api/little/sql/optionToInParam.html","n":"optionToInParam","t":"given optionToInParam[T](using val convert: Conversion[T, InParam]): Conversion[Option[T], InParam]","d":"little/sql/optionToInParam","k":"given"},
{"l":"api/little/sql/optionToInParam.html","n":"apply","t":"def apply(value: Option[T]): InParam","d":"little/sql/optionToInParam","k":"def"},
{"l":"api/little/sql/optionToInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql/optionToInParam","k":"val"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"seqToSeqInParam","t":"given seqToSeqInParam[T](using val convert: Conversion[T, InParam]): Conversion[Seq[T], Seq[InParam]]","d":"little/sql/seqToSeqInParam","k":"given"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"apply","t":"def apply(values: Seq[T]): Seq[InParam]","d":"little/sql/seqToSeqInParam","k":"def"},
{"l":"api/little/sql/seqToSeqInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql/seqToSeqInParam","k":"val"},
{"l":"api/little/sql/shortToInParam$.html","n":"shortToInParam","t":"given shortToInParam: Conversion[Short, InParam]","d":"little/sql/shortToInParam$","k":"given"},
{"l":"api/little/sql/shortToInParam$.html","n":"apply","t":"def apply(value: Short): InParam","d":"little/sql/shortToInParam$","k":"def"},
{"l":"api/little/sql/stringToInParam$.html","n":"stringToInParam","t":"given stringToInParam: Conversion[String, InParam]","d":"little/sql/stringToInParam$","k":"given"},
{"l":"api/little/sql/stringToInParam$.html","n":"apply","t":"def apply(value: String): InParam","d":"little/sql/stringToInParam$","k":"def"},
{"l":"api/little/sql/timeToInParam$.html","n":"timeToInParam","t":"given timeToInParam: Conversion[Time, InParam]","d":"little/sql/timeToInParam$","k":"given"},
{"l":"api/little/sql/timeToInParam$.html","n":"apply","t":"def apply(value: Time): InParam","d":"little/sql/timeToInParam$","k":"def"},
{"l":"api/little/sql/timestampToInParam$.html","n":"timestampToInParam","t":"given timestampToInParam: Conversion[Timestamp, InParam]","d":"little/sql/timestampToInParam$","k":"given"},
{"l":"api/little/sql/timestampToInParam$.html","n":"apply","t":"def apply(value: Timestamp): InParam","d":"little/sql/timestampToInParam$","k":"def"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"tupleToTupleInParam","t":"given tupleToTupleInParam[T](using val convert: Conversion[T, InParam]): Conversion[(String, T), (String, InParam)]","d":"little/sql/tupleToTupleInParam","k":"given"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"apply","t":"def apply(value: (String, T)): (String, InParam)","d":"little/sql/tupleToTupleInParam","k":"def"},
{"l":"api/little/sql/tupleToTupleInParam.html","n":"convert","t":"val convert: Conversion[T, InParam]","d":"little/sql/tupleToTupleInParam","k":"val"},
{"l":"docs/index.html","n":"little-sql","t":"little-sql","d":"","k":"static"}];