pages = [{"l":"index.html","n":"little-sql","t":"little-sql","d":"","k":"static"},
{"l":"little/sql.html","n":"little.sql","t":"package little.sql","d":"little/sql","k":"package"},
{"l":"little/sql.html","n":"ConnectionMethods","t":"def ConnectionMethods(connection: Connection): ConnectionMethods","d":"little/sql","k":"def"},
{"l":"little/sql.html","n":"DataSourceMethods","t":"def DataSourceMethods(dataSource: DataSource): DataSourceMethods","d":"little/sql","k":"def"},
{"l":"little/sql.html","n":"GetBigDecimal","t":"given GetBigDecimal: GetBigDecimal.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetBoolean","t":"given GetBoolean: GetBoolean.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetByte","t":"given GetByte: GetByte.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetDate","t":"given GetDate: GetDate.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetDouble","t":"given GetDouble: GetDouble.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetFloat","t":"given GetFloat: GetFloat.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetInstant","t":"given GetInstant: GetInstant.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetInt","t":"given GetInt: GetInt.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetLocalDate","t":"given GetLocalDate: GetLocalDate.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetLocalDateTime","t":"given GetLocalDateTime: GetLocalDateTime.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetLocalTime","t":"given GetLocalTime: GetLocalTime.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetLong","t":"given GetLong: GetLong.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetShort","t":"given GetShort: GetShort.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetString","t":"given GetString: GetString.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetTime","t":"given GetTime: GetTime.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"GetTimestamp","t":"given GetTimestamp: GetTimestamp.type","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"PreparedStatementMethods","t":"def PreparedStatementMethods(statement: PreparedStatement): PreparedStatementMethods","d":"little/sql","k":"def"},
{"l":"little/sql.html","n":"ResultSetMethods","t":"def ResultSetMethods(resultSet: ResultSet): ResultSetMethods","d":"little/sql","k":"def"},
{"l":"little/sql.html","n":"StatementMethods","t":"def StatementMethods(statement: Statement): StatementMethods","d":"little/sql","k":"def"},
{"l":"little/sql.html","n":"anyToInParam","t":"given anyToInParam: Conversion[Any, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"bigDecimalToInParam","t":"given bigDecimalToInParam: Conversion[BigDecimal, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"booleanToInParam","t":"given booleanToInParam: Conversion[Boolean, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"byteToInParam","t":"given byteToInParam: Conversion[Byte, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"dateToInParam","t":"given dateToInParam: Conversion[Date, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"doubleToInParam","t":"given doubleToInParam: Conversion[Double, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"floatToInParam","t":"given floatToInParam: Conversion[Float, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"instantToInParam","t":"given instantToInParam: Conversion[Instant, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"intToInParam","t":"given intToInParam: Conversion[Int, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"localDateTimeToInParam","t":"given localDateTimeToInParam: Conversion[LocalDateTime, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"localDateToInParam","t":"given localDateToInParam: Conversion[LocalDate, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"localTimeToInParam","t":"given localTimeToInParam: Conversion[LocalTime, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"longToInParam","t":"given longToInParam: Conversion[Long, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"mapToMapInParam","t":"given mapToMapInParam[T](using convert: Conversion[T, InParam]): mapToMapInParam[T]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"noneToInParam","t":"given noneToInParam: Conversion[None.type, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"optionToInParam","t":"given optionToInParam[T](using convert: Conversion[T, InParam]): optionToInParam[T]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"seqToSeqInParam","t":"given seqToSeqInParam[T](using convert: Conversion[T, InParam]): seqToSeqInParam[T]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"shortToInParam","t":"given shortToInParam: Conversion[Short, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"stringToInParam","t":"given stringToInParam: Conversion[String, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"timeToInParam","t":"given timeToInParam: Conversion[Time, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"timestampToInParam","t":"given timestampToInParam: Conversion[Timestamp, InParam]","d":"little/sql","k":"given"},
{"l":"little/sql.html","n":"tupleToTupleInParam","t":"given tupleToTupleInParam[T](using convert: Conversion[T, InParam]): tupleToTupleInParam[T]","d":"little/sql","k":"given"},
{"l":"little/sql/ConnectionMethods.html","n":"ConnectionMethods","t":"class ConnectionMethods(connection: Connection) extends AnyVal","d":"little/sql/ConnectionMethods","k":"class"},
{"l":"little/sql/ConnectionMethods.html","n":"batch","t":"def batch(generator: () => Iterable[String]): Array[Int]","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"batch","t":"def batch(sql: String)(generator: () => Iterable[Seq[InParam]]): Array[Int]","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"execute","t":"def execute[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: Execution => T): T","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"first","t":"def first[T](sql: String, params: Seq[InParam], queryTimeout: Int)(f: ResultSet => T): Option[T]","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"flatMap","t":"def flatMap[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"foreach","t":"def foreach(sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Unit): Unit","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"map","t":"def map[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): Seq[T]","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"query","t":"def query[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): T","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"update","t":"def update[T](sql: String, params: Seq[InParam], queryTimeout: Int)(f: Long => T): T","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"withPreparedStatement","t":"def withPreparedStatement[T](sql: String)(f: PreparedStatement => T): T","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/ConnectionMethods.html","n":"withStatement","t":"def withStatement[T](f: Statement => T): T","d":"little/sql/ConnectionMethods","k":"def"},
{"l":"little/sql/Connector.html","n":"Connector","t":"class Connector(url: String, user: String, password: String, driverClassName: String, driverClassPath: Seq[URL]) extends DataSource","d":"little/sql/Connector","k":"class"},
{"l":"little/sql/Connector.html","n":"getConnection","t":"def getConnection(): Connection","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"getConnection","t":"def getConnection(user: String, password: String): Connection","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"getLogWriter","t":"def getLogWriter(): PrintWriter","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"getLoginTimeout","t":"def getLoginTimeout(): Int","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"getParentLogger","t":"def getParentLogger(): Logger","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"isWrapperFor","t":"def isWrapperFor(kind: Class[_]): Boolean","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"setLogWriter","t":"def setLogWriter(out: PrintWriter): Unit","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"setLoginTimeout","t":"def setLoginTimeout(seconds: Int): Unit","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"this","t":"def this(url: String, user: String, password: String, driverClassName: String)","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"this","t":"def this(url: String, user: String, password: String, driverClassName: String, headDriverClassPath: URL, tailDriverClassPath: URL*)","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/Connector.html","n":"toString","t":"val toString: String","d":"little/sql/Connector","k":"val"},
{"l":"little/sql/Connector.html","n":"unwrap","t":"def unwrap[T](kind: Class[T]): T","d":"little/sql/Connector","k":"def"},
{"l":"little/sql/DataSourceMethods.html","n":"DataSourceMethods","t":"class DataSourceMethods(dataSource: DataSource) extends AnyVal","d":"little/sql/DataSourceMethods","k":"class"},
{"l":"little/sql/DataSourceMethods.html","n":"withConnection","t":"def withConnection[T](f: Connection => T): T","d":"little/sql/DataSourceMethods","k":"def"},
{"l":"little/sql/DataSourceMethods.html","n":"withConnection","t":"def withConnection[T](user: String, password: String)(f: Connection => T): T","d":"little/sql/DataSourceMethods","k":"def"},
{"l":"little/sql/Execution.html","n":"Execution","t":"class Execution","d":"little/sql/Execution","k":"class"},
{"l":"little/sql/Execution.html","n":"count","t":"def count: Int","d":"little/sql/Execution","k":"def"},
{"l":"little/sql/Execution.html","n":"isQuery","t":"def isQuery: Boolean","d":"little/sql/Execution","k":"def"},
{"l":"little/sql/Execution.html","n":"isUpdate","t":"def isUpdate: Boolean","d":"little/sql/Execution","k":"def"},
{"l":"little/sql/Execution.html","n":"resultSet","t":"def resultSet: ResultSet","d":"little/sql/Execution","k":"def"},
{"l":"little/sql/Execution$.html","n":"Execution","t":"object Execution","d":"little/sql/Execution$","k":"object"},
{"l":"little/sql/Execution$.html","n":"apply","t":"def apply(count: Int): Update","d":"little/sql/Execution$","k":"def"},
{"l":"little/sql/Execution$.html","n":"apply","t":"def apply(resultSet: ResultSet): Query","d":"little/sql/Execution$","k":"def"},
{"l":"little/sql/GetBigDecimal$.html","n":"GetBigDecimal","t":"object GetBigDecimal extends GetValue[BigDecimal]","d":"little/sql/GetBigDecimal$","k":"object"},
{"l":"little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): BigDecimal","d":"little/sql/GetBigDecimal$","k":"def"},
{"l":"little/sql/GetBigDecimal$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): BigDecimal","d":"little/sql/GetBigDecimal$","k":"def"},
{"l":"little/sql/GetBoolean$.html","n":"GetBoolean","t":"object GetBoolean extends GetValue[Boolean]","d":"little/sql/GetBoolean$","k":"object"},
{"l":"little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Boolean","d":"little/sql/GetBoolean$","k":"def"},
{"l":"little/sql/GetBoolean$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Boolean","d":"little/sql/GetBoolean$","k":"def"},
{"l":"little/sql/GetByte$.html","n":"GetByte","t":"object GetByte extends GetValue[Byte]","d":"little/sql/GetByte$","k":"object"},
{"l":"little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Byte","d":"little/sql/GetByte$","k":"def"},
{"l":"little/sql/GetByte$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Byte","d":"little/sql/GetByte$","k":"def"},
{"l":"little/sql/GetDate$.html","n":"GetDate","t":"object GetDate extends GetValue[Date]","d":"little/sql/GetDate$","k":"object"},
{"l":"little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Date","d":"little/sql/GetDate$","k":"def"},
{"l":"little/sql/GetDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Date","d":"little/sql/GetDate$","k":"def"},
{"l":"little/sql/GetDouble$.html","n":"GetDouble","t":"object GetDouble extends GetValue[Double]","d":"little/sql/GetDouble$","k":"object"},
{"l":"little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Double","d":"little/sql/GetDouble$","k":"def"},
{"l":"little/sql/GetDouble$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Double","d":"little/sql/GetDouble$","k":"def"},
{"l":"little/sql/GetFloat$.html","n":"GetFloat","t":"object GetFloat extends GetValue[Float]","d":"little/sql/GetFloat$","k":"object"},
{"l":"little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Float","d":"little/sql/GetFloat$","k":"def"},
{"l":"little/sql/GetFloat$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Float","d":"little/sql/GetFloat$","k":"def"},
{"l":"little/sql/GetInstant$.html","n":"GetInstant","t":"object GetInstant extends GetValue[Instant]","d":"little/sql/GetInstant$","k":"object"},
{"l":"little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Instant","d":"little/sql/GetInstant$","k":"def"},
{"l":"little/sql/GetInstant$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Instant","d":"little/sql/GetInstant$","k":"def"},
{"l":"little/sql/GetInt$.html","n":"GetInt","t":"object GetInt extends GetValue[Int]","d":"little/sql/GetInt$","k":"object"},
{"l":"little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Int","d":"little/sql/GetInt$","k":"def"},
{"l":"little/sql/GetInt$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Int","d":"little/sql/GetInt$","k":"def"},
{"l":"little/sql/GetLocalDate$.html","n":"GetLocalDate","t":"object GetLocalDate extends GetValue[LocalDate]","d":"little/sql/GetLocalDate$","k":"object"},
{"l":"little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDate","d":"little/sql/GetLocalDate$","k":"def"},
{"l":"little/sql/GetLocalDate$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDate","d":"little/sql/GetLocalDate$","k":"def"},
{"l":"little/sql/GetLocalDateTime$.html","n":"GetLocalDateTime","t":"object GetLocalDateTime extends GetValue[LocalDateTime]","d":"little/sql/GetLocalDateTime$","k":"object"},
{"l":"little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalDateTime","d":"little/sql/GetLocalDateTime$","k":"def"},
{"l":"little/sql/GetLocalDateTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalDateTime","d":"little/sql/GetLocalDateTime$","k":"def"},
{"l":"little/sql/GetLocalTime$.html","n":"GetLocalTime","t":"object GetLocalTime extends GetValue[LocalTime]","d":"little/sql/GetLocalTime$","k":"object"},
{"l":"little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): LocalTime","d":"little/sql/GetLocalTime$","k":"def"},
{"l":"little/sql/GetLocalTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): LocalTime","d":"little/sql/GetLocalTime$","k":"def"},
{"l":"little/sql/GetLong$.html","n":"GetLong","t":"object GetLong extends GetValue[Long]","d":"little/sql/GetLong$","k":"object"},
{"l":"little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Long","d":"little/sql/GetLong$","k":"def"},
{"l":"little/sql/GetLong$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Long","d":"little/sql/GetLong$","k":"def"},
{"l":"little/sql/GetShort$.html","n":"GetShort","t":"object GetShort extends GetValue[Short]","d":"little/sql/GetShort$","k":"object"},
{"l":"little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Short","d":"little/sql/GetShort$","k":"def"},
{"l":"little/sql/GetShort$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Short","d":"little/sql/GetShort$","k":"def"},
{"l":"little/sql/GetString$.html","n":"GetString","t":"object GetString extends GetValue[String]","d":"little/sql/GetString$","k":"object"},
{"l":"little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): String","d":"little/sql/GetString$","k":"def"},
{"l":"little/sql/GetString$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): String","d":"little/sql/GetString$","k":"def"},
{"l":"little/sql/GetTime$.html","n":"GetTime","t":"object GetTime extends GetValue[Time]","d":"little/sql/GetTime$","k":"object"},
{"l":"little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Time","d":"little/sql/GetTime$","k":"def"},
{"l":"little/sql/GetTime$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Time","d":"little/sql/GetTime$","k":"def"},
{"l":"little/sql/GetTimestamp$.html","n":"GetTimestamp","t":"object GetTimestamp extends GetValue[Timestamp]","d":"little/sql/GetTimestamp$","k":"object"},
{"l":"little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): Timestamp","d":"little/sql/GetTimestamp$","k":"def"},
{"l":"little/sql/GetTimestamp$.html","n":"apply","t":"def apply(rs: ResultSet, label: String): Timestamp","d":"little/sql/GetTimestamp$","k":"def"},
{"l":"little/sql/GetValue.html","n":"GetValue","t":"trait GetValue[T] extends GetValueByIndex[T] with GetValueByLabel[T]","d":"little/sql/GetValue","k":"trait"},
{"l":"little/sql/GetValueByIndex.html","n":"GetValueByIndex","t":"trait GetValueByIndex[T]","d":"little/sql/GetValueByIndex","k":"trait"},
{"l":"little/sql/GetValueByIndex.html","n":"apply","t":"def apply(rs: ResultSet, index: Int): T","d":"little/sql/GetValueByIndex","k":"def"},
{"l":"little/sql/GetValueByLabel.html","n":"GetValueByLabel","t":"trait GetValueByLabel[T]","d":"little/sql/GetValueByLabel","k":"trait"},
{"l":"little/sql/GetValueByLabel.html","n":"apply","t":"def apply(rs: ResultSet, label: String): T","d":"little/sql/GetValueByLabel","k":"def"},
{"l":"little/sql/InParam.html","n":"InParam","t":"trait InParam","d":"little/sql/InParam","k":"trait"},
{"l":"little/sql/InParam.html","n":"isNull","t":"def isNull: Boolean","d":"little/sql/InParam","k":"def"},
{"l":"little/sql/InParam.html","n":"sqlType","t":"def sqlType: Int","d":"little/sql/InParam","k":"def"},
{"l":"little/sql/InParam.html","n":"value","t":"def value: Any","d":"little/sql/InParam","k":"def"},
{"l":"little/sql/InParam$.html","n":"InParam","t":"object InParam","d":"little/sql/InParam$","k":"object"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply[T](value: T, isNull: Boolean, sqlType: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply[T](value: T, sqlType: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: String): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Boolean): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Byte): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Short): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Int): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Long): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Float): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Double): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: BigDecimal): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Date): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Time): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Timestamp): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalDate): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalTime): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: LocalDateTime): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$.html","n":"apply","t":"def apply(value: Instant): InParam","d":"little/sql/InParam$","k":"def"},
{"l":"little/sql/InParam$$Null$.html","n":"Null","t":"object Null extends InParam","d":"little/sql/InParam$$Null$","k":"object"},
{"l":"little/sql/InParam$$Null$.html","n":"isNull","t":"val isNull: Boolean","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"little/sql/InParam$$Null$.html","n":"sqlType","t":"val sqlType: Int","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"little/sql/InParam$$Null$.html","n":"value","t":"val value: Any","d":"little/sql/InParam$$Null$","k":"val"},
{"l":"little/sql/PreparedStatementMethods.html","n":"PreparedStatementMethods","t":"class PreparedStatementMethods(statement: PreparedStatement) extends AnyVal","d":"little/sql/PreparedStatementMethods","k":"class"},
{"l":"little/sql/PreparedStatementMethods.html","n":"addBatch","t":"def addBatch(params: Seq[InParam]): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"execute","t":"def execute[T](params: Seq[InParam])(f: Execution => T): T","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"first","t":"def first[T](params: Seq[InParam])(f: ResultSet => T): Option[T]","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"flatMap","t":"def flatMap[T](params: Seq[InParam])(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"foreach","t":"def foreach(params: Seq[InParam])(f: ResultSet => Unit): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"map","t":"def map[T](params: Seq[InParam])(f: ResultSet => T): Seq[T]","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"query","t":"def query[T](params: Seq[InParam])(f: ResultSet => T): T","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"set","t":"def set(index: Int, value: InParam): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"set","t":"def set(params: Seq[InParam]): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"setInstant","t":"def setInstant(index: Int, value: Instant): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"setLocalDate","t":"def setLocalDate(index: Int, value: LocalDate): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"setLocalDateTime","t":"def setLocalDateTime(index: Int, value: LocalDateTime): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"setLocalTime","t":"def setLocalTime(index: Int, value: LocalTime): Unit","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/PreparedStatementMethods.html","n":"update","t":"def update[T](params: Seq[InParam])(f: Long => T): T","d":"little/sql/PreparedStatementMethods","k":"def"},
{"l":"little/sql/Query.html","n":"Query","t":"class Query(resultSet: ResultSet) extends Execution","d":"little/sql/Query","k":"class"},
{"l":"little/sql/Query.html","n":"count","t":"def count: Int","d":"little/sql/Query","k":"def"},
{"l":"little/sql/Query.html","n":"isQuery","t":"val isQuery: Boolean","d":"little/sql/Query","k":"val"},
{"l":"little/sql/Query.html","n":"isUpdate","t":"val isUpdate: Boolean","d":"little/sql/Query","k":"val"},
{"l":"little/sql/QueryBuilder.html","n":"QueryBuilder","t":"trait QueryBuilder","d":"little/sql/QueryBuilder","k":"trait"},
{"l":"little/sql/QueryBuilder.html","n":"execute","t":"def execute[T](handler: Execution => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"fetchSize","t":"def fetchSize: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"fetchSize","t":"def fetchSize(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"first","t":"def first[T](f: ResultSet => T)(using conn: Connection): Option[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"flatMap","t":"def flatMap[T](f: ResultSet => Iterable[T])(using conn: Connection): Seq[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"fold","t":"def fold[T](init: T)(op: (T, ResultSet) => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"foreach","t":"def foreach(f: ResultSet => Unit)(using conn: Connection): Unit","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"map","t":"def map[T](f: ResultSet => T)(using conn: Connection): Seq[T]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"maxRows","t":"def maxRows: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"maxRows","t":"def maxRows(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"params","t":"def params: Seq[InParam]","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"params","t":"def params(values: Seq[InParam]): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"params","t":"def params(one: InParam, more: InParam*): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"params","t":"def params(values: Map[String, InParam]): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"params","t":"def params(one: (String, InParam), more: (String, InParam)*): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"query","t":"def query[T](f: ResultSet => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"queryTimeout","t":"def queryTimeout: Int","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"queryTimeout","t":"def queryTimeout(value: Int): QueryBuilder","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"sql","t":"def sql: String","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder.html","n":"update","t":"def update[T](f: Long => T)(using conn: Connection): T","d":"little/sql/QueryBuilder","k":"def"},
{"l":"little/sql/QueryBuilder$.html","n":"QueryBuilder","t":"object QueryBuilder","d":"little/sql/QueryBuilder$","k":"object"},
{"l":"little/sql/QueryBuilder$.html","n":"apply","t":"def apply(sql: String): QueryBuilder","d":"little/sql/QueryBuilder$","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"ResultSetMethods","t":"class ResultSetMethods(resultSet: ResultSet) extends AnyVal","d":"little/sql/ResultSetMethods","k":"class"},
{"l":"little/sql/ResultSetMethods.html","n":"flatMap","t":"def flatMap[T](f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"fold","t":"def fold[T](init: T)(op: (T, ResultSet) => T): T","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"foreach","t":"def foreach(f: ResultSet => Unit): Unit","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"get","t":"def get[T](index: Int)(using getValue: GetValueByIndex[T]): T","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"get","t":"def get[T](label: String)(using getValue: GetValueByLabel[T]): T","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getColumnCount","t":"def getColumnCount(): Int","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getColumnLabels","t":"def getColumnLabels(): Seq[String]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getInstant","t":"def getInstant(index: Int): Instant","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getInstant","t":"def getInstant(label: String): Instant","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalDate","t":"def getLocalDate(index: Int): LocalDate","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalDate","t":"def getLocalDate(label: String): LocalDate","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalDateTime","t":"def getLocalDateTime(index: Int): LocalDateTime","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalDateTime","t":"def getLocalDateTime(label: String): LocalDateTime","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalTime","t":"def getLocalTime(index: Int): LocalTime","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getLocalTime","t":"def getLocalTime(label: String): LocalTime","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getOption","t":"def getOption[T](index: Int)(using getValue: GetValueByIndex[T]): Option[T]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getOption","t":"def getOption[T](label: String)(using getValue: GetValueByLabel[T]): Option[T]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getOrElse","t":"def getOrElse[T](index: Int, default: => T)(using getValue: GetValueByIndex[T]): T","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"getOrElse","t":"def getOrElse[T](label: String, default: => T)(using getValue: GetValueByLabel[T]): T","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"map","t":"def map[T](f: ResultSet => T): Seq[T]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/ResultSetMethods.html","n":"mapNext","t":"def mapNext[T](f: ResultSet => T): Option[T]","d":"little/sql/ResultSetMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"StatementMethods","t":"class StatementMethods(statement: Statement) extends AnyVal","d":"little/sql/StatementMethods","k":"class"},
{"l":"little/sql/StatementMethods.html","n":"execute","t":"def execute[T](sql: String)(f: Execution => T): T","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"first","t":"def first[T](sql: String)(f: ResultSet => T): Option[T]","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"flatMap","t":"def flatMap[T](sql: String)(f: ResultSet => Iterable[T]): Seq[T]","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"foreach","t":"def foreach(sql: String)(f: ResultSet => Unit): Unit","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"map","t":"def map[T](sql: String)(f: ResultSet => T): Seq[T]","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"query","t":"def query[T](sql: String)(f: ResultSet => T): T","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/StatementMethods.html","n":"update","t":"def update[T](sql: String)(f: Long => T): T","d":"little/sql/StatementMethods","k":"def"},
{"l":"little/sql/Update.html","n":"Update","t":"class Update(count: Int) extends Execution","d":"little/sql/Update","k":"class"},
{"l":"little/sql/Update.html","n":"isQuery","t":"val isQuery: Boolean","d":"little/sql/Update","k":"val"},
{"l":"little/sql/Update.html","n":"isUpdate","t":"val isUpdate: Boolean","d":"little/sql/Update","k":"val"},
{"l":"little/sql/Update.html","n":"resultSet","t":"def resultSet: ResultSet","d":"little/sql/Update","k":"def"},
{"l":"docs/index.html","n":"little-sql","t":"little-sql","d":"","k":"static"}];