pages = [{"l":"index.html#","e":false,"i":"","n":"little-sql","t":"little-sql","d":"","k":"static","x":""},
{"l":"little/sql.html#","e":false,"i":"","n":"little.sql","t":"little.sql","d":"","k":"package","x":""},
{"l":"little/sql.html#ConnectionMethods-3c0","e":false,"i":"","n":"ConnectionMethods","t":"ConnectionMethods(connection: Connection): ConnectionMethods","d":"little.sql","k":"def","x":""},
{"l":"little/sql.html#DataSourceMethods-fffff57a","e":false,"i":"","n":"DataSourceMethods","t":"DataSourceMethods(dataSource: DataSource): DataSourceMethods","d":"little.sql","k":"def","x":""},
{"l":"little/sql.html#PreparedStatementMethods-9cc","e":false,"i":"","n":"PreparedStatementMethods","t":"PreparedStatementMethods(statement: PreparedStatement): PreparedStatementMethods","d":"little.sql","k":"def","x":""},
{"l":"little/sql.html#ResultSetMethods-bb2","e":false,"i":"","n":"ResultSetMethods","t":"ResultSetMethods(resultSet: ResultSet): ResultSetMethods","d":"little.sql","k":"def","x":""},
{"l":"little/sql.html#StatementMethods-fffff206","e":false,"i":"","n":"StatementMethods","t":"StatementMethods(statement: Statement): StatementMethods","d":"little.sql","k":"def","x":""},
{"l":"little/sql.html#anyToInParam-0","e":false,"i":"","n":"anyToInParam","t":"anyToInParam: Conversion[Any, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#bigDecimalToInParam-0","e":false,"i":"","n":"bigDecimalToInParam","t":"bigDecimalToInParam: Conversion[BigDecimal, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#booleanToInParam-0","e":false,"i":"","n":"booleanToInParam","t":"booleanToInParam: Conversion[Boolean, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#byteToInParam-0","e":false,"i":"","n":"byteToInParam","t":"byteToInParam: Conversion[Byte, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#dateToInParam-0","e":false,"i":"","n":"dateToInParam","t":"dateToInParam: Conversion[Date, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#doubleToInParam-0","e":false,"i":"","n":"doubleToInParam","t":"doubleToInParam: Conversion[Double, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#floatToInParam-0","e":false,"i":"","n":"floatToInParam","t":"floatToInParam: Conversion[Float, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getBigDecimalByIndex-0","e":false,"i":"","n":"getBigDecimalByIndex","t":"getBigDecimalByIndex: GetValueByIndex[BigDecimal]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getBigDecimalByLabel-0","e":false,"i":"","n":"getBigDecimalByLabel","t":"getBigDecimalByLabel: GetValueByLabel[BigDecimal]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getBooleanByIndex-0","e":false,"i":"","n":"getBooleanByIndex","t":"getBooleanByIndex: GetValueByIndex[Boolean]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getBooleanByLabel-0","e":false,"i":"","n":"getBooleanByLabel","t":"getBooleanByLabel: GetValueByLabel[Boolean]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getByteByIndex-0","e":false,"i":"","n":"getByteByIndex","t":"getByteByIndex: GetValueByIndex[Byte]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getByteByLabel-0","e":false,"i":"","n":"getByteByLabel","t":"getByteByLabel: GetValueByLabel[Byte]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getDateByIndex-0","e":false,"i":"","n":"getDateByIndex","t":"getDateByIndex: GetValueByIndex[Date]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getDateByLabel-0","e":false,"i":"","n":"getDateByLabel","t":"getDateByLabel: GetValueByLabel[Date]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getDoubleByIndex-0","e":false,"i":"","n":"getDoubleByIndex","t":"getDoubleByIndex: GetValueByIndex[Double]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getDoubleByLabel-0","e":false,"i":"","n":"getDoubleByLabel","t":"getDoubleByLabel: GetValueByLabel[Double]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getFloatByIndex-0","e":false,"i":"","n":"getFloatByIndex","t":"getFloatByIndex: GetValueByIndex[Float]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getFloatByLabel-0","e":false,"i":"","n":"getFloatByLabel","t":"getFloatByLabel: GetValueByLabel[Float]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getInstantByIndex-0","e":false,"i":"","n":"getInstantByIndex","t":"getInstantByIndex: GetValueByIndex[Instant]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getInstantByLabel-0","e":false,"i":"","n":"getInstantByLabel","t":"getInstantByLabel: GetValueByLabel[Instant]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getIntByIndex-0","e":false,"i":"","n":"getIntByIndex","t":"getIntByIndex: GetValueByIndex[Int]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getIntByLabel-0","e":false,"i":"","n":"getIntByLabel","t":"getIntByLabel: GetValueByLabel[Int]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalDateByIndex-0","e":false,"i":"","n":"getLocalDateByIndex","t":"getLocalDateByIndex: GetValueByIndex[LocalDate]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalDateByLabel-0","e":false,"i":"","n":"getLocalDateByLabel","t":"getLocalDateByLabel: GetValueByLabel[LocalDate]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalDateTimeByIndex-0","e":false,"i":"","n":"getLocalDateTimeByIndex","t":"getLocalDateTimeByIndex: GetValueByIndex[LocalDateTime]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalDateTimeByLabel-0","e":false,"i":"","n":"getLocalDateTimeByLabel","t":"getLocalDateTimeByLabel: GetValueByLabel[LocalDateTime]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalTimeByIndex-0","e":false,"i":"","n":"getLocalTimeByIndex","t":"getLocalTimeByIndex: GetValueByIndex[LocalTime]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLocalTimeByLabel-0","e":false,"i":"","n":"getLocalTimeByLabel","t":"getLocalTimeByLabel: GetValueByLabel[LocalTime]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLongByIndex-0","e":false,"i":"","n":"getLongByIndex","t":"getLongByIndex: GetValueByIndex[Long]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getLongByLabel-0","e":false,"i":"","n":"getLongByLabel","t":"getLongByLabel: GetValueByLabel[Long]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getShortByIndex-0","e":false,"i":"","n":"getShortByIndex","t":"getShortByIndex: GetValueByIndex[Short]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getShortByLabel-0","e":false,"i":"","n":"getShortByLabel","t":"getShortByLabel: GetValueByLabel[Short]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getStringByIndex-0","e":false,"i":"","n":"getStringByIndex","t":"getStringByIndex: GetValueByIndex[String]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getStringByLabel-0","e":false,"i":"","n":"getStringByLabel","t":"getStringByLabel: GetValueByLabel[String]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getTimeByIndex-0","e":false,"i":"","n":"getTimeByIndex","t":"getTimeByIndex: GetValueByIndex[Time]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getTimeByLabel-0","e":false,"i":"","n":"getTimeByLabel","t":"getTimeByLabel: GetValueByLabel[Time]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getTimestampByIndex-0","e":false,"i":"","n":"getTimestampByIndex","t":"getTimestampByIndex: GetValueByIndex[Timestamp]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#getTimestampByLabel-0","e":false,"i":"","n":"getTimestampByLabel","t":"getTimestampByLabel: GetValueByLabel[Timestamp]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#instantToInParam-0","e":false,"i":"","n":"instantToInParam","t":"instantToInParam: Conversion[Instant, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#intToInParam-0","e":false,"i":"","n":"intToInParam","t":"intToInParam: Conversion[Int, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#localDateTimeToInParam-0","e":false,"i":"","n":"localDateTimeToInParam","t":"localDateTimeToInParam: Conversion[LocalDateTime, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#localDateToInParam-0","e":false,"i":"","n":"localDateToInParam","t":"localDateToInParam: Conversion[LocalDate, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#localTimeToInParam-0","e":false,"i":"","n":"localTimeToInParam","t":"localTimeToInParam: Conversion[LocalTime, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#longToInParam-0","e":false,"i":"","n":"longToInParam","t":"longToInParam: Conversion[Long, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#mapToMapInParam-bf8","e":false,"i":"","n":"mapToMapInParam","t":"mapToMapInParam[T](using convert: Conversion[T, InParam]): mapToMapInParam[T]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#noneToInParam-0","e":false,"i":"","n":"noneToInParam","t":"noneToInParam: Conversion[None.type, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#optionToInParam-ad","e":false,"i":"","n":"optionToInParam","t":"optionToInParam[T](using convert: Conversion[T, InParam]): optionToInParam[T]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#seqToSeqInParam-618","e":false,"i":"","n":"seqToSeqInParam","t":"seqToSeqInParam[T](using convert: Conversion[T, InParam]): seqToSeqInParam[T]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#shortToInParam-0","e":false,"i":"","n":"shortToInParam","t":"shortToInParam: Conversion[Short, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#stringToInParam-0","e":false,"i":"","n":"stringToInParam","t":"stringToInParam: Conversion[String, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#timeToInParam-0","e":false,"i":"","n":"timeToInParam","t":"timeToInParam: Conversion[Time, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#timestampToInParam-0","e":false,"i":"","n":"timestampToInParam","t":"timestampToInParam: Conversion[Timestamp, InParam]","d":"little.sql","k":"given","x":""},
{"l":"little/sql.html#tupleToTupleInParam-138","e":false,"i":"","n":"tupleToTupleInParam","t":"tupleToTupleInParam[T](using convert: Conversion[T, InParam]): tupleToTupleInParam[T]","d":"little.sql","k":"given","x":""},
{"l":"little/sql/ConnectionMethods.html#","e":false,"i":"","n":"ConnectionMethods","t":"ConnectionMethods(connection: Connection) extends AnyVal","d":"little.sql","k":"class","x":""},
{"l":"little/sql/ConnectionMethods.html#batch-fffffe39","e":false,"i":"","n":"batch","t":"batch(generator: () => Iterable[String]): Array[Int]","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#batch-fffff05e","e":false,"i":"","n":"batch","t":"batch(sql: String)(generator: () => Iterable[Seq[InParam]]): Array[Int]","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#execute-4fe","e":false,"i":"","n":"execute","t":"execute[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: Execution => T): T","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#executeUpdate-cdb","e":false,"i":"","n":"executeUpdate","t":"executeUpdate(sql: String, params: Seq[InParam], queryTimeout: Int): Long","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#first-fffff188","e":false,"i":"","n":"first","t":"first[T](sql: String, params: Seq[InParam], queryTimeout: Int)(f: ResultSet => T): Option[T]","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#flatMap-fffffe56","e":false,"i":"","n":"flatMap","t":"flatMap[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Iterable[T]): Seq[T]","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#foreach-506","e":false,"i":"","n":"foreach","t":"foreach(sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => Unit): Unit","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#map-fffffe56","e":false,"i":"","n":"map","t":"map[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): Seq[T]","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#query-4fe","e":false,"i":"","n":"query","t":"query[T](sql: String, params: Seq[InParam], queryTimeout: Int, maxRows: Int, fetchSize: Int)(f: ResultSet => T): T","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#update-75e","e":false,"i":"","n":"update","t":"update[T](sql: String, params: Seq[InParam], queryTimeout: Int)(f: Long => T): T","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#withPreparedStatement-4ce","e":false,"i":"","n":"withPreparedStatement","t":"withPreparedStatement[T](sql: String)(f: PreparedStatement => T): T","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/ConnectionMethods.html#withStatement-5d3","e":false,"i":"","n":"withStatement","t":"withStatement[T](f: Statement => T): T","d":"little.sql.ConnectionMethods","k":"def","x":""},
{"l":"little/sql/Connector.html#","e":false,"i":"","n":"Connector","t":"Connector(url: String, user: String, password: String, driverClassName: String, driverClassLoader: ClassLoader) extends DataSource","d":"little.sql","k":"class","x":""},
{"l":"little/sql/Connector.html#getConnection-46a","e":false,"i":"","n":"getConnection","t":"getConnection(): Connection","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#getConnection-960","e":false,"i":"","n":"getConnection","t":"getConnection(user: String, password: String): Connection","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#getLogWriter-5e4","e":false,"i":"","n":"getLogWriter","t":"getLogWriter(): PrintWriter","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#getLoginTimeout-ffffff27","e":false,"i":"","n":"getLoginTimeout","t":"getLoginTimeout(): Int","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#getParentLogger-fffff0bf","e":false,"i":"","n":"getParentLogger","t":"getParentLogger(): Logger","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#isWrapperFor-93c","e":false,"i":"","n":"isWrapperFor","t":"isWrapperFor(kind: Class[_]): Boolean","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#setLogWriter-fffff230","e":false,"i":"","n":"setLogWriter","t":"setLogWriter(out: PrintWriter): Unit","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#setLoginTimeout-fffff3b3","e":false,"i":"","n":"setLoginTimeout","t":"setLoginTimeout(seconds: Int): Unit","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#<init>-fffffa54","e":false,"i":"","n":"this","t":"this(url: String, user: String, password: String, driverClassName: String, driverClassPath: Seq[URL])","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#<init>-fffffea9","e":false,"i":"","n":"this","t":"this(url: String, user: String, password: String, driverClassName: String)","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/Connector.html#toString-0","e":false,"i":"","n":"toString","t":"toString: String","d":"little.sql.Connector","k":"val","x":""},
{"l":"little/sql/Connector.html#unwrap-3e6","e":false,"i":"","n":"unwrap","t":"unwrap[T](kind: Class[T]): T","d":"little.sql.Connector","k":"def","x":""},
{"l":"little/sql/DataSourceMethods.html#","e":false,"i":"","n":"DataSourceMethods","t":"DataSourceMethods(dataSource: DataSource) extends AnyVal","d":"little.sql","k":"class","x":""},
{"l":"little/sql/DataSourceMethods.html#withConnection-5d3","e":false,"i":"","n":"withConnection","t":"withConnection[T](f: Connection => T): T","d":"little.sql.DataSourceMethods","k":"def","x":""},
{"l":"little/sql/DataSourceMethods.html#withConnection-dc9","e":false,"i":"","n":"withConnection","t":"withConnection[T](user: String, password: String)(f: Connection => T): T","d":"little.sql.DataSourceMethods","k":"def","x":""},
{"l":"little/sql/Execution.html#","e":false,"i":"","n":"Execution","t":"Execution","d":"little.sql","k":"class","x":""},
{"l":"little/sql/Execution.html#count-0","e":false,"i":"","n":"count","t":"count: Long","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/Execution.html#isQuery-0","e":false,"i":"","n":"isQuery","t":"isQuery: Boolean","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/Execution.html#isUpdate-0","e":false,"i":"","n":"isUpdate","t":"isUpdate: Boolean","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/Execution.html#resultSet-0","e":false,"i":"","n":"resultSet","t":"resultSet: ResultSet","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/Execution$.html#","e":false,"i":"","n":"Execution","t":"Execution","d":"little.sql","k":"object","x":""},
{"l":"little/sql/Execution$.html#apply-fffff93d","e":false,"i":"","n":"apply","t":"apply(count: Long): Update","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/Execution$.html#apply-d89","e":false,"i":"","n":"apply","t":"apply(resultSet: ResultSet): Query","d":"little.sql.Execution","k":"def","x":""},
{"l":"little/sql/GetValue.html#","e":false,"i":"","n":"GetValue","t":"GetValue[T] extends GetValueByIndex[T], GetValueByLabel[T]","d":"little.sql","k":"trait","x":""},
{"l":"little/sql/GetValueByIndex.html#","e":false,"i":"","n":"GetValueByIndex","t":"GetValueByIndex[T]","d":"little.sql","k":"trait","x":""},
{"l":"little/sql/GetValueByIndex.html#apply-e1","e":false,"i":"","n":"apply","t":"apply(rs: ResultSet, index: Int): T","d":"little.sql.GetValueByIndex","k":"def","x":""},
{"l":"little/sql/GetValueByLabel.html#","e":false,"i":"","n":"GetValueByLabel","t":"GetValueByLabel[T]","d":"little.sql","k":"trait","x":""},
{"l":"little/sql/GetValueByLabel.html#apply-5f1","e":false,"i":"","n":"apply","t":"apply(rs: ResultSet, label: String): T","d":"little.sql.GetValueByLabel","k":"def","x":""},
{"l":"little/sql/InParam.html#","e":false,"i":"","n":"InParam","t":"InParam","d":"little.sql","k":"trait","x":""},
{"l":"little/sql/InParam.html#isNull-0","e":false,"i":"","n":"isNull","t":"isNull: Boolean","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam.html#sqlType-0","e":false,"i":"","n":"sqlType","t":"sqlType: Int","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam.html#value-0","e":false,"i":"","n":"value","t":"value: Any","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#","e":false,"i":"","n":"InParam","t":"InParam","d":"little.sql","k":"object","x":""},
{"l":"little/sql/InParam$.html#apply-fffffefb","e":false,"i":"","n":"apply","t":"apply[T](value: T, isNull: Boolean, sqlType: Int): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffffc53","e":false,"i":"","n":"apply","t":"apply[T](value: T, sqlType: Int): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff255","e":false,"i":"","n":"apply","t":"apply(value: String): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffffa90","e":false,"i":"","n":"apply","t":"apply(value: Boolean): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff800","e":false,"i":"","n":"apply","t":"apply(value: Byte): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff3e4","e":false,"i":"","n":"apply","t":"apply(value: Short): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffffe97","e":false,"i":"","n":"apply","t":"apply(value: Int): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff874","e":false,"i":"","n":"apply","t":"apply(value: Long): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-9c4","e":false,"i":"","n":"apply","t":"apply(value: Float): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff089","e":false,"i":"","n":"apply","t":"apply(value: Double): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffffdbf","e":false,"i":"","n":"apply","t":"apply(value: BigDecimal): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-eea","e":false,"i":"","n":"apply","t":"apply(value: Date): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff849","e":false,"i":"","n":"apply","t":"apply(value: Time): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-eba","e":false,"i":"","n":"apply","t":"apply(value: Timestamp): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-734","e":false,"i":"","n":"apply","t":"apply(value: LocalDate): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffff093","e":false,"i":"","n":"apply","t":"apply(value: LocalTime): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-fffffae1","e":false,"i":"","n":"apply","t":"apply(value: LocalDateTime): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$.html#apply-41c","e":false,"i":"","n":"apply","t":"apply(value: Instant): InParam","d":"little.sql.InParam","k":"def","x":""},
{"l":"little/sql/InParam$$Null$.html#","e":false,"i":"","n":"Null","t":"Null extends InParam","d":"little.sql.InParam","k":"object","x":""},
{"l":"little/sql/InParam$$Null$.html#isNull-0","e":false,"i":"","n":"isNull","t":"isNull: Boolean","d":"little.sql.InParam.Null","k":"val","x":""},
{"l":"little/sql/InParam$$Null$.html#sqlType-0","e":false,"i":"","n":"sqlType","t":"sqlType: Int","d":"little.sql.InParam.Null","k":"val","x":""},
{"l":"little/sql/InParam$$Null$.html#value-0","e":false,"i":"","n":"value","t":"value: Any","d":"little.sql.InParam.Null","k":"val","x":""},
{"l":"little/sql/PreparedStatementMethods.html#","e":false,"i":"","n":"PreparedStatementMethods","t":"PreparedStatementMethods(statement: PreparedStatement) extends AnyVal","d":"little.sql","k":"class","x":""},
{"l":"little/sql/PreparedStatementMethods.html#addBatch-fffff9b7","e":false,"i":"","n":"addBatch","t":"addBatch(params: Seq[InParam]): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#execute-a08","e":false,"i":"","n":"execute","t":"execute[T](params: Seq[InParam])(f: Execution => T): T","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#first-932","e":false,"i":"","n":"first","t":"first[T](params: Seq[InParam])(f: ResultSet => T): Option[T]","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#flatMap-9e0","e":false,"i":"","n":"flatMap","t":"flatMap[T](params: Seq[InParam])(f: ResultSet => Iterable[T]): Seq[T]","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#foreach-8d2","e":false,"i":"","n":"foreach","t":"foreach(params: Seq[InParam])(f: ResultSet => Unit): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#map-9e0","e":false,"i":"","n":"map","t":"map[T](params: Seq[InParam])(f: ResultSet => T): Seq[T]","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#query-a08","e":false,"i":"","n":"query","t":"query[T](params: Seq[InParam])(f: ResultSet => T): T","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#set-fffff723","e":false,"i":"","n":"set","t":"set(index: Int, value: InParam): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#set-fffff9b7","e":false,"i":"","n":"set","t":"set(params: Seq[InParam]): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#setInstant-eb1","e":false,"i":"","n":"setInstant","t":"setInstant(index: Int, value: Instant): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#setLocalDate-f89","e":false,"i":"","n":"setLocalDate","t":"setLocalDate(index: Int, value: LocalDate): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#setLocalDateTime-bb6","e":false,"i":"","n":"setLocalDateTime","t":"setLocalDateTime(index: Int, value: LocalDateTime): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#setLocalTime-fffff7e8","e":false,"i":"","n":"setLocalTime","t":"setLocalTime(index: Int, value: LocalTime): Unit","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/PreparedStatementMethods.html#update-a08","e":false,"i":"","n":"update","t":"update[T](params: Seq[InParam])(f: Long => T): T","d":"little.sql.PreparedStatementMethods","k":"def","x":""},
{"l":"little/sql/Query.html#","e":false,"i":"","n":"Query","t":"Query(resultSet: ResultSet) extends Execution","d":"little.sql","k":"class","x":""},
{"l":"little/sql/Query.html#count-0","e":false,"i":"","n":"count","t":"count: Long","d":"little.sql.Query","k":"def","x":""},
{"l":"little/sql/Query.html#isQuery-0","e":false,"i":"","n":"isQuery","t":"isQuery: Boolean","d":"little.sql.Query","k":"val","x":""},
{"l":"little/sql/Query.html#isUpdate-0","e":false,"i":"","n":"isUpdate","t":"isUpdate: Boolean","d":"little.sql.Query","k":"val","x":""},
{"l":"little/sql/QueryBuilder.html#","e":false,"i":"","n":"QueryBuilder","t":"QueryBuilder","d":"little.sql","k":"trait","x":""},
{"l":"little/sql/QueryBuilder.html#execute-5bd","e":false,"i":"","n":"execute","t":"execute[T](handler: Execution => T)(using conn: Connection): T","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#executeUpdate-fffffe2e","e":false,"i":"","n":"executeUpdate","t":"executeUpdate()(using conn: Connection): Long","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#fetchSize-0","e":false,"i":"","n":"fetchSize","t":"fetchSize: Int","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#fetchSize-fffffee4","e":false,"i":"","n":"fetchSize","t":"fetchSize(value: Int): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#first-fffff767","e":false,"i":"","n":"first","t":"first[T](f: ResultSet => T)(using conn: Connection): Option[T]","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#flatMap-fffff4d5","e":false,"i":"","n":"flatMap","t":"flatMap[T](f: ResultSet => Iterable[T])(using conn: Connection): Seq[T]","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#fold-aef","e":false,"i":"","n":"fold","t":"fold[T](init: T)(op: (T, ResultSet) => T)(using conn: Connection): T","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#foreach-245","e":false,"i":"","n":"foreach","t":"foreach(f: ResultSet => Unit)(using conn: Connection): Unit","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#map-fffff4d5","e":false,"i":"","n":"map","t":"map[T](f: ResultSet => T)(using conn: Connection): Seq[T]","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#maxRows-0","e":false,"i":"","n":"maxRows","t":"maxRows: Int","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#maxRows-fffffee4","e":false,"i":"","n":"maxRows","t":"maxRows(value: Int): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#params-0","e":false,"i":"","n":"params","t":"params: Seq[InParam]","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#params-ffffff60","e":false,"i":"","n":"params","t":"params(values: Seq[InParam]): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#params-230","e":false,"i":"","n":"params","t":"params(one: InParam, more: InParam*): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#params-fffff9c3","e":false,"i":"","n":"params","t":"params(values: Map[String, InParam]): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#params-b6e","e":false,"i":"","n":"params","t":"params(one: (String, InParam), more: (String, InParam)*): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#query-5bd","e":false,"i":"","n":"query","t":"query[T](f: ResultSet => T)(using conn: Connection): T","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#queryTimeout-0","e":false,"i":"","n":"queryTimeout","t":"queryTimeout: Int","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#queryTimeout-fffffee4","e":false,"i":"","n":"queryTimeout","t":"queryTimeout(value: Int): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#sql-0","e":false,"i":"","n":"sql","t":"sql: String","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder.html#update-5bd","e":false,"i":"","n":"update","t":"update[T](f: Long => T)(using conn: Connection): T","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/QueryBuilder$.html#","e":false,"i":"","n":"QueryBuilder","t":"QueryBuilder","d":"little.sql","k":"object","x":""},
{"l":"little/sql/QueryBuilder$.html#apply-fffff1e6","e":false,"i":"","n":"apply","t":"apply(sql: String): QueryBuilder","d":"little.sql.QueryBuilder","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#","e":false,"i":"","n":"ResultSetMethods","t":"ResultSetMethods(resultSet: ResultSet) extends AnyVal","d":"little.sql","k":"class","x":""},
{"l":"little/sql/ResultSetMethods.html#flatMap-66b","e":false,"i":"","n":"flatMap","t":"flatMap[T](f: ResultSet => Iterable[T]): Seq[T]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#fold-fffff9e1","e":false,"i":"","n":"fold","t":"fold[T](init: T)(op: (T, ResultSet) => T): T","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#foreach-c9d","e":false,"i":"","n":"foreach","t":"foreach(f: ResultSet => Unit): Unit","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#get-ffffff71","e":false,"i":"","n":"get","t":"get[T](index: Int)(using getValue: GetValueByIndex[T]): T","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#get-13","e":false,"i":"","n":"get","t":"get[T](label: String)(using getValue: GetValueByLabel[T]): T","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getColumnCount-ffffff27","e":false,"i":"","n":"getColumnCount","t":"getColumnCount(): Int","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getColumnLabels-fffffa2b","e":false,"i":"","n":"getColumnLabels","t":"getColumnLabels(): Seq[String]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getInstant-ffffffa5","e":false,"i":"","n":"getInstant","t":"getInstant(index: Int): Instant","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getInstant-fffffc27","e":false,"i":"","n":"getInstant","t":"getInstant(label: String): Instant","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalDate-e7d","e":false,"i":"","n":"getLocalDate","t":"getLocalDate(index: Int): LocalDate","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalDate-27f","e":false,"i":"","n":"getLocalDate","t":"getLocalDate(label: String): LocalDate","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalDateTime-fffffeea","e":false,"i":"","n":"getLocalDateTime","t":"getLocalDateTime(index: Int): LocalDateTime","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalDateTime-fffff1ec","e":false,"i":"","n":"getLocalDateTime","t":"getLocalDateTime(label: String): LocalDateTime","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalTime-19c","e":false,"i":"","n":"getLocalTime","t":"getLocalTime(index: Int): LocalTime","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getLocalTime-59e","e":false,"i":"","n":"getLocalTime","t":"getLocalTime(label: String): LocalTime","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getOption-fffffb1b","e":false,"i":"","n":"getOption","t":"getOption[T](index: Int)(using getValue: GetValueByIndex[T]): Option[T]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getOption-cbd","e":false,"i":"","n":"getOption","t":"getOption[T](label: String)(using getValue: GetValueByLabel[T]): Option[T]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getOrElse-c15","e":false,"i":"","n":"getOrElse","t":"getOrElse[T](index: Int, default: => T)(using getValue: GetValueByIndex[T]): T","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#getOrElse-fb7","e":false,"i":"","n":"getOrElse","t":"getOrElse[T](label: String, default: => T)(using getValue: GetValueByLabel[T]): T","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#map-66b","e":false,"i":"","n":"map","t":"map[T](f: ResultSet => T): Seq[T]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/ResultSetMethods.html#next-27d","e":false,"i":"","n":"next","t":"next[T](f: ResultSet => T): Option[T]","d":"little.sql.ResultSetMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#","e":false,"i":"","n":"StatementMethods","t":"StatementMethods(statement: Statement) extends AnyVal","d":"little.sql","k":"class","x":""},
{"l":"little/sql/StatementMethods.html#execute-4ce","e":false,"i":"","n":"execute","t":"execute[T](sql: String)(f: Execution => T): T","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#first-fffff6f8","e":false,"i":"","n":"first","t":"first[T](sql: String)(f: ResultSet => T): Option[T]","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#flatMap-226","e":false,"i":"","n":"flatMap","t":"flatMap[T](sql: String)(f: ResultSet => Iterable[T]): Seq[T]","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#foreach-1d8","e":false,"i":"","n":"foreach","t":"foreach(sql: String)(f: ResultSet => Unit): Unit","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#map-226","e":false,"i":"","n":"map","t":"map[T](sql: String)(f: ResultSet => T): Seq[T]","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#query-4ce","e":false,"i":"","n":"query","t":"query[T](sql: String)(f: ResultSet => T): T","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/StatementMethods.html#update-4ce","e":false,"i":"","n":"update","t":"update[T](sql: String)(f: Long => T): T","d":"little.sql.StatementMethods","k":"def","x":""},
{"l":"little/sql/Update.html#","e":false,"i":"","n":"Update","t":"Update(count: Long) extends Execution","d":"little.sql","k":"class","x":""},
{"l":"little/sql/Update.html#isQuery-0","e":false,"i":"","n":"isQuery","t":"isQuery: Boolean","d":"little.sql.Update","k":"val","x":""},
{"l":"little/sql/Update.html#isUpdate-0","e":false,"i":"","n":"isUpdate","t":"isUpdate: Boolean","d":"little.sql.Update","k":"val","x":""},
{"l":"little/sql/Update.html#resultSet-0","e":false,"i":"","n":"resultSet","t":"resultSet: ResultSet","d":"little.sql.Update","k":"def","x":""}];